window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPCODE_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\appcode.vmoptions",
  "APPDATA": "C:\\Users\\user\\AppData\\Roaming",
  "asl.log": "Destination=file",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_7424_NYMGSTECZWYGRJTO",
  "CLION_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\clion.vmoptions",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "WIN-TQJ7MPT9I2H",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DATAGRIP_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\datagrip.vmoptions",
  "DATASPELL_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\dataspell.vmoptions",
  "DEVECOSTUDIO_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\devecostudio.vmoptions",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GATEWAY_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\gateway.vmoptions",
  "GIT_ASKPASS": "c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "GOLAND_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\goland.vmoptions",
  "HOME": "C:\\Users\\user",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\user",
  "IDEA_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\idea.vmoptions",
  "INIT_CWD": "D:\\WEB\\rolling-school\\react js\\week1",
  "JETBRAINSCLIENT_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\jetbrainsclient.vmoptions",
  "JETBRAINS_CLIENT_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\jetbrains_client.vmoptions",
  "LANG": "ru_RU.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\user\\AppData\\Local",
  "LOGONSERVER": "\\\\WIN-TQJ7MPT9I2H",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\user\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\user\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\user\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\user\\.npm-init.js",
  "npm_config_local_prefix": "D:\\WEB\\rolling-school\\react js\\week1",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\user\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\user\\.npmrc",
  "npm_config_user_agent": "npm/8.19.2 node/v16.18.0 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "start",
  "npm_lifecycle_script": "react-dotenv && react-scripts start",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "D:\\WEB\\rolling-school\\react js\\week1\\package.json",
  "npm_package_name": "lern-react-ts",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OPENSSL_CONF": "C:\\Program Files\\PostgreSQL\\psqlODBC\\etc\\openssl.cnf",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "D:\\WEB\\rolling-school\\react js\\week1\\node_modules\\.bin;D:\\WEB\\rolling-school\\react js\\node_modules\\.bin;D:\\WEB\\rolling-school\\node_modules\\.bin;D:\\WEB\\node_modules\\.bin;D:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\AMD\\ATI.ACE\\Core-Static;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\user\\AppData\\Roaming\\npm;C:\\Users\\user\\.dotnet\\tools;C:\\Program Files\\heroku\\bin",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PHPSTORM_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\phpstorm.vmoptions",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
  "PROCESSOR_LEVEL": "21",
  "PROCESSOR_REVISION": "0200",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\user\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PYCHARM_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\pycharm.vmoptions",
  "RIDER_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\rider.vmoptions",
  "RUBYMINE_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\rubymine.vmoptions",
  "SESSIONNAME": "Console",
  "STUDIO_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\studio.vmoptions",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\user\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.75.0",
  "TMP": "C:\\Users\\user\\AppData\\Local\\Temp",
  "USERDOMAIN": "WIN-TQJ7MPT9I2H",
  "USERDOMAIN_ROAMINGPROFILE": "WIN-TQJ7MPT9I2H",
  "USERNAME": "user",
  "USERPROFILE": "C:\\Users\\user",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-5276344014-sock",
  "VSCODE_INJECTION": "1",
  "WEBIDE_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\webide.vmoptions",
  "WEBSTORM_VM_OPTIONS": "D:\\program\\$ WEB_PROGRAM\\jetbra\\vmoptions\\webstorm.vmoptions",
  "windir": "C:\\Windows"
};